name: Automated SonyLIV JSON Updater

on:
  schedule:
    - cron: '*/10 * * * *' 
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download JSON
        run: |
          curl -sS -o sonyliv.json "https://raw.githubusercontent.com/drmlive/sliv-live-events/refs/heads/main/sonyliv.json"
          echo "Last sync: $(date)" > sliv.txt

      - name: Configure Git User
        run: |
          git config --global user.email "kajju3864@gmail.com"
          git config --global user.name "kajju027"

      - name: Commit and Push
        run: |
          git add sonyliv.json sliv.txt
          git commit -m "System Sync: SonyLIV Update âœ… $(date)" || exit 0
          git push
          
