name: Automated SonyLIV JSON Updater

on:
  schedule:
    - cron: '*/7 * * * *' 
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download JSON and Update Log
        run: |
          curl -sS -o sonyliv.json "https://raw.githubusercontent.com/drmlive/sliv-live-events/refs/heads/main/sonyliv.json"
          export TZ="Asia/Kolkata"
          echo "ðŸš€ System Synced Successfully BY Sayan | IST: $(date +'%Y-%m-%d %H:%M:%S') | ID: $RANDOM" >> sliv.txt

      - name: Configure Git User
        run: |
          git config --global user.email "kajju3864@gmail.com"
          git config --global user.name "kajju027"

      - name: Commit and Push
        run: |
          export TZ="Asia/Kolkata"
          git add sonyliv.json sliv.txt
          git commit -m "SonyLIV Database Updated âœ… [$(date +'%d-%m-%Y %H:%M')] #$RANDOM" --allow-empty
          git push
          
